import { Metadata } from "next";
import { ErrorWrapper } from "./error-wrapper";
// import '@/app/globals.css'; // tailwind globals

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - TranHoangLong",
    template: "%s | TranHoangLong",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
          }}
        >
          <p>Header</p>
        </header>

        {/* <ErrorWrapper>{children}</ErrorWrapper> */}
        {children}
        
        <footer
          style={{
            backgroundColor: "lightgreen",
            padding: "1rem",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
